package com.apps.kim.todo.tools.classes

/**
Created by KIM on 25.09.2019
 **/

const val BASE_URL = "http://quotes.rest/"
const val EMPTY_STRING = ""
const val EMPTY_INT = 0
const val EMPTY_LONG = 0L
const val DEFAULT_INT = -1
const val TIMEZONE_DATE_PATTERN = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
const val NO_ALPHA = 1F
const val HALF_ALPHA = .5F
const val EVERY_DAY: Long = 86400000
const val DATA_PENDING_ID: String = "DATA_PENDING_ID"
const val CHANNEL_ID: String = "CHANNEL_ID"
const val KEY_LIMIT_MAX_IMAGE = "KEY_LIMIT_MAX_IMAGE"
const val KEY_LIMIT_MIN_IMAGE = "KEY_LIMIT_MIN_IMAGE"
const val KEY_DATA_RESULT = "KEY_DATA_RESULT"

//SharedPreferences
const val APP_PREFERENCES = "APP_PREFERENCES"
const val PREF_USER_ID = "PREF_USER_ID"
const val PREF_FIRST_OPEN = "PREF_FIRST_OPEN"
const val PREF_PERIODS = "PREF_PERIODS"
const val PREF_TAG = "PREF_TAG"
const val PREF_QUOTE = "PREF_QUOTE"
const val PREF_SOUND_1 = "PREF_SOUND_1"
const val PREF_SOUND_2 = "PREF_SOUND_2"
const val PREF_SOUND_3 = "PREF_SOUND_3"
const val PREF_SOUND_4 = "PREF_SOUND_4"
const val PREF_SOUND_5 = "PREF_SOUND_5"
const val PREF_SOUND_6 = "PREF_SOUND_6"
const val PREF_SOUND_NAME_1 = "PREF_SOUND_NAME_1"
const val PREF_SOUND_NAME_2 = "PREF_SOUND_NAME_2"
const val PREF_SOUND_NAME_3 = "PREF_SOUND_NAME_3"
const val PREF_SOUND_NAME_4 = "PREF_SOUND_NAME_4"
const val PREF_SOUND_NAME_5 = "PREF_SOUND_NAME_5"
const val PREF_SOUND_NAME_6 = "PREF_SOUND_NAME_6"
const val PREF_START_TEXT_1 = "PREF_START_TEXT_1"
const val PREF_START_TEXT_2 = "PREF_START_TEXT_2"
const val PREF_START_TEXT_3 = "PREF_START_TEXT_3"
const val PREF_START_TEXT_4 = "PREF_START_TEXT_4"
const val PREF_START_TEXT_5 = "PREF_START_TEXT_5"
const val PREF_START_TEXT_6 = "PREF_START_TEXT_6"
const val PREF_IMG_1 = "PREF_IMG_1"
const val PREF_IMG_2 = "PREF_IMG_2"
const val PREF_IMG_3 = "PREF_IMG_3"
const val PREF_IMG_4 = "PREF_IMG_4"
const val PREF_IMG_5 = "PREF_IMG_5"
const val PREF_IMG_6 = "PREF_IMG_6"
const val PREF_BACK_1 = "PREF_BACK_1"
const val PREF_BACK_2 = "PREF_BACK_2"
const val PREF_BACK_3 = "PREF_BACK_3"
const val PREF_BACK_4 = "PREF_BACK_4"
const val PREF_BACK_5 = "PREF_BACK_5"
const val PREF_BACK_6 = "PREF_BACK_6"

//buttons
const val BUTTON_1 = "BUTTON_1"
const val BUTTON_2 = "BUTTON_2"
const val BUTTON_3 = "BUTTON_3"
const val BUTTON_4 = "BUTTON_4"
const val BUTTON_5 = "BUTTON_5"
const val BUTTON_6 = "BUTTON_6"

//bundles
const val BUNDLE_BUTTON = "BUNDLE_BUTTON"
const val BUNDLE_LIST = "BUNDLE_LIST"

//tags
const val TAG_TODO = "TAG_TODO"
const val TAG_FAMILY = "TAG_FAMILY"
const val TAG_ALARMS = "TAG_ALARMS"
const val TAG_MEDICINES = "TAG_MEDICINES"
const val TAG_WORKOUT = "TAG_WORKOUT"
const val TAG_DIET = "TAG_DIET"

//request
const val REQUEST_GALLERY_IMG1 = 1021
const val REQUEST_GALLERY_IMG2 = 1022
const val REQUEST_GALLERY_IMG3 = 1023
const val REQUEST_GALLERY_IMG4 = 1024
const val REQUEST_GALLERY_IMG5 = 1025
const val REQUEST_GALLERY_IMG6 = 1026
const val REQUEST_GALLERY_BACK1 = 1126
const val REQUEST_GALLERY_BACK2 = 1226
const val REQUEST_GALLERY_BACK3 = 1326
const val REQUEST_GALLERY_BACK4 = 1426
const val REQUEST_GALLERY_BACK5 = 1526
const val REQUEST_GALLERY_BACK6 = 1626
const val REQUEST_AUTHENTICATION = 1700

//fragments
const val START_FRAGMENT = "START_FRAGMENT"
const val HOME_FRAGMENT = "HOME_FRAGMENT"
const val LIST_FRAGMENT = "LIST_FRAGMENT"
const val ADD_FRAGMENT = "ADD_FRAGMENT"
const val CUSTOMIZE_FRAGMENT = "CUSTOMIZE_FRAGMENT"
const val DETAILS_FRAGMENT = "DETAILS_FRAGMENT"
const val EDIT_FRAGMENT = "EDIT_FRAGMENT"
const val DATE_FRAGMENT = "DATE_FRAGMENT"
const val TIME_FRAGMENT = "TIME_FRAGMENT"
const val LOGIN_FRAGMENT = "LOGIN_FRAGMENT"